### ISSUE TITLE
Issue with @ in password

### ISSUE THREAD

**Issue by vaibhavdobriyal** [retrography/OrientR#15]
Hi,

The program is unable to handle in case passwords containing @ - the same may be simply handled by replacing the '@' char by %40. 

Thanks for the wonderful utility and I will be happy to fix!

BR
Dobi

**Comment by retrography** [comment]
Hi Dobi,

Please go ahead and fix. There are several known issues as well, but
unfortunately I am too busy to work on this right now. But I promise to
verify and integrate your pull request within a week or so.
